### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by rhaynes74** [maxnd/fbnotex#1]
Hi - looks like an interesting project.   I have a few questions.   Does your editor allow mathjax? I was also wondering if it could be organized the other way around, files would have notes associated with them?  Can files be linked?

**Comment by maxnd** [comment]
Hi, the editor does not allow mathjax syntax. Anyway, since the Markdown formatting has been implemented from scratch, mathjax formatting could be done as well. This could be very tough, though, since I guess it would be necessary to create a bitmap in memory with the formula to be shown starting from the mathjax code, and then show the bitmap below the code itself. I'm not interested in this functionality, but some people out there may do this according to the GPL 3 license of the code.

A file cannot be associated to more notes, but a note with a one or more files attached can be linked to other notes with one or more files attached. Files cannot be linked, but only the notes they belong to.

**Comment by rhaynes74** [comment]
Thanks for the information.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
